### ISSUE TITLE
Will no longer be updated to the Raku ecosystem

### ISSUE THREAD

**Issue by lizmat** [atweiden/config-toml#10]
Hello,

Thank you for the time and effort you have put in what is now the [Raku Programming Language](https://raku.org).  The language and its ecosystem are [moving forward](https://github.com/Raku/problem-solving/pull/318).

This means that these distributions:

- https://github.com/atweiden/config-toml
- https://github.com/atweiden/crane
- https://github.com/atweiden/digest-xxhash
- https://github.com/atweiden/file-path-resolve
- https://github.com/atweiden/file-presence
- https://github.com/atweiden/mktxn
- https://github.com/atweiden/txn-parser
- https://github.com/atweiden/txn-remarshal

will no longer be checked for updates by the Raku ecosystem.

This means that you will need to move your module to the [zef ecosystem](https://deathbykeystroke.com/articles/20210120-faq-zef-ecosystem.html) on the next update you make to these distributions.  Otherwise your update will simply not be seen by the ecosystem.

If you are no longer interested in maintaining these distributions, you can have these distributions moved to [Raku Community Modules Adoption Center](https://github.com/raku-community-modules/), where members of the Raku Community will take care of them.

This can be as easy as confirming that in a response to this issue.

Again, thank you for your time and efforts!

On behalf of the Raku Steering Council,

Elizabeth Mattijsen

**Comment by atweiden** [comment]
Ok

**Comment by atweiden** [comment]
@lizmat I’d like to transfer config-toml, crane and digest-xxhash to @raku-community-modules. How do I proceed?

**Comment by lizmat** [comment]
I've sent you an invite: after accepting you should be able to transfer these modules yourself.

I assume you will archive the other ones and so they can be removed from the active ecosystem (but still be available from the REA).

**Comment by atweiden** [comment]
Thanks. Done.

**Comment by lizmat** [comment]
Thanks!  Working on re-issuing them to the zef ecosystem now

**Comment by lizmat** [comment]
All three now in zef ecosystem: [Crane](https://raku.land/zef:raku-community-modules/Crane), [Config::TOML](https://raku.land/zef:raku-community-modules/Config::TOML), [Digest::xxHash](https://raku.land/zef:raku-community-modules/Digest::xxHash)
