### ISSUE TITLE
"git tag" your code

### ISSUE THREAD

**Issue by AntonOks** [atweiden/config-toml#9]
Hi.

I know the RAKU eco system, say ZEF, and develops are a bit "different" then other tools and developers, but could you please "git tag" your code with the same version as in the [META6.JSON](https://github.com/atweiden/config-toml/blob/a6fde025a469989dd1f648a054e0ca325bb73503/META6.json#L4)?

THANKS!!!

**Comment by atweiden** [comment]
I can, but I’d like to understand better the necessity of this. Do you have a particular use case in mind, e.g. you would prefer downloading a release version from https://github.com/atweiden/config-toml/releases/download/0.0.01.tar.gz? If this is a new requirement of Zef, I’m sorry to say I was completely unaware of it. I’ve never had an issue doing `zef install Config::TOML`.

**Comment by AntonOks** [comment]
> I can, but I’d like to understand better the necessity of this. Do you have a particular use case in mind, e.g. you would prefer downloading a release version from https://github.com/atweiden/config-toml/releases/download/0.0.01.tar.gz? If this is a new requirement of Zef, I’m sorry to say I was completely unaware of it. I’ve never had an issue doing `zef install Config::TOML`.

Hi.

Well, in general it's more or less about making SW builds "reproducible".

My use case is ["Rakudo Star" and it's modules](https://github.com/rakudo/star/blob/master/etc/modules.txt).
To be more precise, it's about how RSTAR ["fetches" the required Rakudo Star modules](https://github.com/rakudo/star/blob/2fe3fcdcc31cd557f61c9efb4bfa0f769cb343fa/lib/actions/fetch.bash#L89) to prepare the later build aka "dist" and following "install"....

**Comment by atweiden** [comment]
Tags created for both Config::TOML and Crane. I wasn’t aware my modules were included in Rakudo Star. That’s nice to know.

**Comment by AntonOks** [comment]
> Tags created for both Config::TOML and Crane. I wasn’t aware my modules were included in Rakudo Star. That’s nice to know.

THANK YOU!!!
